language: go

sudo: false

notifications:
    email:
        on_success: change
        on_failure: always

go:
    - 1.11.x
    - 1.12.x
    - tip

os:
    - linux
    - osx

before_install:
    - GO_FILES=$(go list ./... | grep -v /vendor/ | grep -v /test-fixtures/)
    - go get -v golang.org/x/lint/golint
    - go get -v honnef.co/go/tools/cmd/staticcheck
    - go get -v github.com/mdempsky/unconvert
    - go get -v github.com/mdempsky/maligned

install: true

script:
    - golint -set_exit_status $GO_FILES
    - staticcheck $GO_FILES
    - unconvert $GO_FILES
    - maligned $GO_FILES
    - go test -race -v $GO_FILES
